name: Build project

on:
  - push
  - pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneOSX
            customImage: unityci/editor:2022.3.9f1-mac-mono-2

          - targetPlatform: StandaloneWindows64
            customImage: unityci/editor:2022.3.9f1-windows-mono-2.0

          - targetPlatform: WebGL
            customImage: unityci/editor:2022.3.9f1-webgl-2

          - targetPlatform: StandaloneLinux64
            customImage: unityci/editor:2022.3.9f1-linux-il2cpp-2

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          customImage: ${{ matrix.customImage }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}
